apiVersion: v2
name: a2rchi
description: A RAG chat bot
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: postgresql
  condition: postgresql.enabled
  repository: https://charts.bitnami.com/bitnami
  version: '>=15.5.38'
