apiVersion: v1
kind: Service
metadata:
  name: {{ include "a2rchi.fullname" . }}
  labels:
    {{- include "a2rchi.labels" . | nindent 4 }}
  name: {{ include "a2rchi.fullname" . }}-chat
spec:
  ports:
    - name: chat-port
      port: {{ .Values.chat.externalPort }}
      targetPort: {{ .Values.chat.port }}
  selector:
    service: {{ include "a2rchi.fullname" . }}-chat
