apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: a2rchi-test
  name: {{ include "a2rchi.fullname" . }}-chromadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
