apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "a2rchi.labels" . | nindent 4 }}
  name: {{ include "a2rchi.fullname" . }}-chromadb
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: {{ include "a2rchi.fullname" . }}-chromadb    
